package.json
src/API/Mist.js
src/containers/Network/NodeConfig.css
src/containers/Network/NodeConfig.jsx
yarn.lock

This PR adds ethereum-react-components/NodeSettings component to mist-ui

feat: Add ethereum-react-components/NodeSettings

---

.prettierrc
src/containers/Network/NodeSetup/ClientConfigForm.jsx
src/containers/Network/NodeSetup/ClientDownload.jsx
src/containers/Network/NodeSetup/ClientSelect.jsx
src/containers/Network/NodeSetup/index.js
src/containers/Network/Terminal.jsx

This PR connects the NodeSetup client option fields, please use in conjunction with [mist-shell#51](https://github.com/ethereum/mist-shell/pull/51)

feat: connect NodeSetup fields

---

README.md
package.json

chore: renames project

---

src/NodesTab.js
src/containers/Network/GethConfig/VersionList.jsx

hot fixes for typography and list loading state.

fix: font + list load

---

.github/PULL_REQUEST_TEMPLATE.md

Encourages closing issues in PR templates (+ kanban usage).

chore: PR template addition

---

src/components/Nodes/index.js

Cleans up and organizes the `Nodes/index.js` file to get ready for more nodes
Also adds version number on hover

chore: refactor `Nodes/index.js`

---

src/store/client/actions.js
src/store/client/reducer.js
src/store/client/reducer.test.js

- writes reducer tests
- cleans up reducer code
- `error` is a top-level key in flux standard actions (FSA)

chore: reducer tests

---

.circleci/config.yml
src/components/Nodes/GethConfig/VersionList.jsx
src/components/Nodes/Terminal.jsx
src/store/client/actions.js
src/store/client/reducer.js
src/store/client/reducer.test.js

updates master branch

---

src/components/Nodes/ServicesNav.js

fix: displays selected version on correct client

---

src/components/Nodes/Terminal.jsx

fix: terminal height

---

src/components/Nodes/ClientConfig/DynamicConfigForm.jsx
src/components/Nodes/ClientConfig/index.js
src/components/Nodes/index.js
src/store/client/actions.js
src/store/client/reducer.js
src/store/client/reducer.test.js

Passes plugin information to node settings pane, and generates a form based on config types.
Closes https://github.com/ethereum/grid/issues/174.

Dynamic config pane

---

src/components/GenericProvider.js
src/components/Nodes/ClientConfig/ConfigForm.jsx
src/components/Nodes/ClientConfig/DynamicConfigForm.jsx
src/components/Nodes/ClientConfig/VersionList.jsx
src/components/Nodes/ClientConfig/VersionListItem.jsx
src/components/Nodes/NodeInfo/NodeInfoDot.jsx
src/components/Nodes/NodeInfo/index.js
src/components/Nodes/ServicesNav.js
src/components/Nodes/ServicesNavListItem.js
src/components/Nodes/Terminal.jsx
src/components/Nodes/index.js
src/components/Webview/UrlBar.jsx
src/components/popups/ConnectAccount/ConnectAccount.js
src/components/shared/Button.js
src/components/shared/Notification.js
src/components/shared/Select.js

Hey!
It makes an improvement on component property types. Some of the changes might be too strict, please let me know if any, so I can tune them. (e.g. required `classes`)
Resolves #13.

refactor: Improvement for PropType definitions

---

src/components/App.js
src/components/NavTabs.js
src/components/shared/HelpFab.js

Adds a feedback button to the corner. It links to a [google form](https://forms.gle/CDr5tJPhqoJqoS8e8).
Closes https://github.com/ethereum/grid/issues/113.

feat: adds help button that links to a feedback form

---

src/components/Nodes/Terminal/TerminalInput.js
src/components/Nodes/Terminal/index.js

* Adds an input below the terminal for writing to `stdin`
* Scroll through past terminal input with up and down arrows
(FYI: blank output lines of `> ` shown in above gif are now being ignored)
---
Closes https://github.com/ethereum/grid/issues/212

feat: Terminal Input

---

src/components/Nodes/ClientConfig/DynamicConfigForm/FlagPreview.jsx
src/components/Nodes/ClientConfig/DynamicConfigForm/FormItem.jsx
src/components/Nodes/ClientConfig/DynamicConfigForm/index.js
src/components/Nodes/index.js
src/store/client/actions.js
src/store/client/reducer.js
src/store/client/reducer.test.js

First pass at custom settable flags
---
Closes https://github.com/ethereum/grid/issues/247

feat: custom settable flags

---

src/components/Nodes/Terminal/TerminalInput.js
src/components/Nodes/Terminal/index.js

Protects terminal input as `***` if checkbox is selected

feat: protect terminal input

---

src/components/Apps/AppItem.js
src/components/Nodes/ClientConfig/VersionList/VersionListItem.js
src/components/shared/Button.js
src/components/shared/HelpFab.js
src/theme.js

Refreshes the theme a bit: colors, hover states, button gradients.
Just took a stab at this. I know everyone's got opinions about colors. 😅 
Closes https://github.com/ethereum/grid/issues/319

chore: update theme

---

src/components/App.js
src/components/Nodes/ClientConfig/VersionList/VersionListItem.js
src/components/Nodes/ClientConfig/index.js
src/components/Nodes/ServicesNavListItem.js
src/index.js
src/theme.js

Enables dark mode changing MUI theme. Light mode was left on the code for further iteration.

feat: Dark mode

---

src/components/Nodes/ClientConfig/DynamicConfigForm/FlagPreview.jsx
src/components/Nodes/ClientConfig/DynamicConfigForm/index.js

Warns users not to "take flags from strangers"
Closes https://github.com/ethereum/grid/issues/354

feat: warn when using custom flags

---

src/components/Nodes/ClientConfig/VersionList/index.js
src/store/client/actions.js
src/store/client/reducer.js

Stores and gets selected release in `config.json`
---
To be paired with https://github.com/ethereum/grid/pull/370

feat: store selected release

---

package.json
src/components/App.js
src/components/Apps/AppItem.js
src/components/Apps/index.js
src/components/Plugins/PluginConfig/AboutPlugin.js
src/components/Plugins/PluginConfig/DependencyCard.js
src/components/Plugins/PluginConfig/DynamicConfigForm/FlagPreview.js
src/components/Plugins/PluginConfig/VersionList/VersionListItem.js
src/components/Plugins/PluginConfig/VersionList/VersionsAvailableText.js
src/components/Plugins/PluginConfig/VersionList/index.js
src/components/Plugins/PluginConfig/index.js
src/components/Plugins/PluginsNav.js
src/components/Plugins/PluginsNavListItem.js
src/components/Plugins/Terminal/index.js
src/components/Window.js
src/index.css
src/index.js
src/scrollbar-fix.css
src/theme.js
yarn.lock

UI Improvements

---

src/store/plugin/actions.js
src/store/plugin/clientService.js
src/store/plugin/pluginService.js

Hotfix for 1) a plugin start error, and 2) killing off a couple intervals that weren't previously.
before:

fix: uncleared peer and sync intervals

---

src/components/Plugins/PluginConfig/VersionList/VersionsAvailableText.js
src/components/Plugins/PluginConfig/VersionList/index.js

Fixes refresh button by passing in missing prop
Fixes https://github.com/ethereum/grid/issues/285

fix: refresh button

---

src/components/Plugins/PluginConfig/index.js
src/components/Plugins/PluginsNav.js
src/components/Plugins/PluginsNavListItem.js
src/store/plugin/pluginService.js

Merge dev into master to prepare for release

Merge dev into master
