README.md
This PR adds instructions to the bottom of `README.md` with instructions on how to use a local copy of ethereum-react-components in dev.
=> feat: add readme instructions to run local version of ethereum-react-components

src/App.js, src/Routes.js, src/components/SidebarTab.js, src/index.js
- removes `Wallet` and `Browser` navigation tabs
- sets `NodeSetup` as root route
- temporarily resolves breaking bug on load
Re: breaking bug, `Mist.window` is undefined, so `Mist.window.getArgs()` breaks on line 33 of `src/index.js`. The preload file in `mist-shell` only passes along a `geth` key on the `Mist` window object.
=> fix: hide out of scope features

README.md, docs/CONTRIBUTING.md
Introduces some contribution context/guidelines. Closes https://github.com/ethereum/mist-shell/issues/41.
This [template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) was helpful in coming up with ideas.
=> fix: adds contribution guidelines

package.json, src/API/Mist.js, src/index.js, yarn.lock
- Slightly better hot fix for running the app locally, with or without mist-shell.
- Bumps component lib version.
- When testing with `mist-shell`: `window.Mist` is made available by the preload file, `mist-ui` uses that API. (Depends on PR in mist-shell: https://github.com/ethereum/mist-shell/pull/42.)
- When testing with only `mist-ui`: no `window.Mist` is available, so mock API is returned instead.
=> fix: bootup with or without mist-shell

package.json, src/containers/Network/ClientDownload.jsx, yarn.lock
- bumps component lib
- uses new spinner and progress components
- closes https://github.com/ethereum/mist-shell/issues/54
=> fix: mui spinner + progress

src/containers/Network/GethConfig/VersionList.jsx, src/containers/Network/GethConfig/index.js, src/containers/Network/Terminal.jsx, src/theme.js
introduces toggle-able way to follow logs, i.e. you stay scrolled to the bottom of the log file, viewing most recent logs without having to scroll down manually.
inspiration from Travis CI, including language used on their button: "Follow Logs"
=> feat: follow logs

src/components/Nodes/NodeInfo/NodeInfoBox.jsx
Updates stale block color from red to orange. Lines up with recent change of dot color to orange when blocks are stale.
Closes https://github.com/ethereum/grid/issues/83
=> fix: stale block color

package.json, src/API/Mist.js, src/components/Nodes/GethConfig/ConfigForm.jsx, src/components/Nodes/GethConfig/VersionList.jsx, src/components/Nodes/GethConfig/index.js, src/components/Nodes/NodeInfo/NodeInfoBox.jsx, src/components/Nodes/NodeInfo/NodeInfoDot.jsx, src/components/Nodes/Terminal.jsx, src/index.js, src/store/client/gethService.js, src/store/client/reducer.js, src/store/index.js, src/store/rootReducer.js, yarn.lock
Adds `redux-persist` to persist the store
`redux-persist`
Closes https://github.com/ethereum/grid/issues/23
=> feat: redux persist

src/components/Nodes/GethConfig/ConfigForm.jsx
Changes selector from file to directory
Thx @varshard https://github.com/ethereum/grid-ui/issues/39
=> fix: directory selector. closes #39

src/components/Nodes/GethConfig/VersionList.jsx
Ensures previously selected release still exists after fetching local releases.
Fixes https://github.com/ethereum/grid/issues/130
=> fix: ensure previously selected release still exists

src/components/Nodes/Terminal.jsx
It removes fixed height of the terminal and enables totally fluid terminal window, while allowing internal scrolling.
Front-end fix of https://github.com/ethereum/grid/issues/157
=> Fix: makes terminal pane totally fluid with internal scrolling

src/components/Nodes/ClientConfig/VersionList.jsx
Makes versionList height follow window height.
Closes https://github.com/ethereum/grid/issues/168.
=> Style: adds fluid height to versionList component

src/components/Nodes/ClientConfig/ConfigForm.jsx, src/components/Nodes/ClientConfig/VersionList.jsx, src/components/Nodes/ClientConfig/VersionListItem.jsx, src/components/Nodes/ClientConfig/index.js, src/components/Nodes/ServicesNav.js, src/components/Nodes/index.js, src/components/Webview/UrlBar.jsx, src/index.js, src/store/client/actions.js, src/store/client/reducer.js, src/store/index.js, src/store/rootReducer.js
- fixes UI bugs related to connection status when jumping between clients
- fixes tab navigation: 
- when starting client, show Terminal
- when switching clients, show VersionList
- select first downloaded release
- autoselect newly downloaded release
- disables redux-persist for now
- captures a ton of state in redux
- other assorted cleanup
- fixes https://github.com/ethereum/grid/issues/169
- closes https://github.com/ethereum/grid/issues/148
- fixes https://github.com/ethereum/grid/issues/170
- fixes https://github.com/ethereum/grid/issues/154
=> fix: active connection status

src/components/Nodes/ClientConfig/index.js, src/components/Nodes/index.js, src/components/Webview/index.jsx, src/store/client/actions.js, src/store/client/gethService.js, src/store/client/reducer.js
- stubs out NodeInfo until its providing value
- displays accurate client connection status, e.g. "CONNECTED", rather than just "STARTED" or "STOPPED"
closes https://github.com/ethereum/grid/issues/176
fixes https://github.com/ethereum/grid/issues/181
=> fix: captures connection status

src/components/Nodes/ServicesNav.js
disables toggle when another client is running or a release isn't selected
TODO: current redux store architecture prevents us from allowing toggling off a service if it is not actively selected.
closes https://github.com/ethereum/grid/issues/183
=> fix: disable toggle rules

package.json, src/components/Nodes/Terminal.jsx, yarn.lock
Enables colored terminal output, parsing those garbage-like characters that Aleth and potentially other clients use on their output.
[ANSI to React](https://www.npmjs.com/package/ansi-to-react)
https://github.com/ethereum/grid/issues/184
=> style: Enables ansi coloring on terminal output

src/components/Nodes/ServicesNav.js
Heya!
It eliminates unused classes from `classes` object for `ServicesNavListItem` component and resolves warnings of Material-UI which seen on screenshot.
=> fix:  Material-UI "the key provided to the classes property is not implemened" warning

src/components/Nodes/ClientConfig/VersionListItem.jsx
It prevents setState usage in VersionListItem component when the component is already unmounted. 
In following steps for user; 
1. clicks `download version button` 
2. changes the Services from side-tab before download ended.
=> fix: setState error when VersionListItem component already unmounted

src/components/Nodes/ClientConfig/VersionList.jsx
Restores latest version error warning
Closes https://github.com/ethereum/grid/issues/208
=> fix: restore latest version warning

src/components/App.js, src/components/GenericErrorBoundary.js, src/components/Nodes/ClientConfig/index.js, src/store/client/actions.js
- Introduces GenericErrorBoundary and adds boundaries at the app level and at the DynaminConfigForm.
- Fixes a bug that occurs when a service (e.g. Raiden) has settings of object data type instead of array.
- Waiting on the hardcoded geth PR to implement proper error display.
- Future work could make `ErrorBoundary` component more fun or instructive.
Top-level boundary:
DynamicConfigForm-level boundary:
- Closes https://github.com/ethereum/grid/issues/211
=> feat: ErrorBoundary

src/components/shared/HelpFab.js
Implements css fix/hack to keep the feedback btn above the scrollbar.
Reproducing this bug has been unreliable, but it reared its head again. This seems to do the trick.
Before:
After:
Closes https://github.com/ethereum/grid/issues/197
=> fix: fab behind scrollbar

src/components/Apps/AppItem.js, src/components/Apps/index.js, src/components/NavTabs.js, src/components/Webview/UrlBar.jsx, src/components/Webview/index.jsx, src/index.js
Restructures the UI in Nodes and Apps. Available apps are fetched from Grid API (needs changes in Grid to find apps).
It removes disabled & unused tabs. The webview tab is refactored into a "popup" / container window used to display launched apps. 
- the UI becomes cleaner and the concepts easier to understand (no webview tab -> "no browser")
- easier for users to try out apps that make use of the clients
- easier for us to showcase examples and motivate projects
- challenges our architecture to think about two different flows:
1. user wants to configure and start clients as main objective
2. user wants an app that communicate with clients (more UX focused and likely?)
-> apps will eventually be able to define a dependency to clients which are automatically configured and started
Allows …
=> feat: add app view

src/components/Apps/index.js
Adds some padding so the feedback button doesn't cover the launch button of the corner app.
before:
after:
closes https://github.com/ethereum/grid/issues/239
=> fix: feedback btn cover app launch btn

src/components/Nodes/ServicesNavListItem.js, src/lib/flags.js, src/lib/utils.js, src/store/client/actions.js, src/test/settings.test.js
- extracts `generateFlags()` to a new file
- preserves spaces typed by users 
- [test case covering expected flag values with spaces preserved](https://github.com/ethereum/grid-ui/pull/83/files#diff-aff35ec90e4353a3a88190d9356c3185R157)
Closes https://github.com/ethereum/grid/issues/236
=> fix: preserves spaces on flag values

.circleci/config.yml
removes nightly builds, to alleviate the amount of versions being released everyday.
=> ci: disabling nightly builds

src/components/Webview/index.jsx, src/index.css
Fixes apps to show in their window with height:100%;
=> fix: height 100% for apps

package.json
Prevents annoyance from `create-react-app` that opens local server page on every `yarn start`
Passes `BROWSER=none` environment variable to create-react-app starting script.
=> fix: do not open local server on browser

src/components/Nodes/ClientConfig/DynamicConfigForm/FormItem.jsx
Renames `openFolderDialog` to `showOpenDialog` and accepts `file` or `directory` (or `file_multiple` or `directory_multiple`)
Pairs with https://github.com/ethereum/grid/pull/286
=> feat: expands showOpenDialog to accept `file` or `directory`

src/components/Nodes/ServicesNav.js
Displays plugins sorted by their `type`
To test rendering of the list, you can add these plugins to grid `plugins.json`:
```
[
{
"name": "clef",
"displayName": "Clef",
"type": "signer",
"author": {
"name": "Ryan Ghods",
"email": "ryan@ethereum.org",
"address": "84741b205fe071833b97b081a87dc39fae078ff3"
},
"location": "https://github.com/ryanio/grid-clef-plugin"
},
{
"name": "swarm",
"displayName": "Swarm",
"type": "storage",
"author": {
"name": "Philipp Langhans",
"email": "philipp@ethereum.org",
"address": "9fae5e6e2583216f23bdf94f74ceae26e209b31e"
},
"location": "https://github.com/PhilippLgh/grid-swarm-extension"
}
]
```
=> feat: plugin list categories

src/components/Nodes/index.js, src/index.js, src/lib/utils.js, src/store/client/actions.js, src/store/index.js, src/store/middleware.js, src/store/rootReducer.js, src/test/settings.test.js
- ~Uses `redux-persist` to store user's configuration settings in localStorage.~
- Persists plugin settings via the config.json file.
- Introduces some logic to handle when to use rehydrated state.
- Implementation done via redux middleware.
- To test, edit configs and add `"settings": {}` to the top-level keys, save, then restart the app. This change is reflected in this Grid PR: https://github.com/ethereum/grid/pull/311. If you already have a config.json file, however, you will need to make the change manually.
~`redux-persist` (was already installed from previous work, though)~ jk
Closes https://github.com/ethereum/grid/issues/23
=> feat: persist config data

src/components/Nodes/ServicesNav.js
Fixes small warning found in console due to passing of classes as props onto next component. This PR resolves the issue.
The warning found in console:
```index.js:1452 Warning: Material-UI: the key `listSubheader` provided to the classes property is not implemented in ServicesNavListItem.
You can only override one of the following: selected,serviceName,hoverableListItem,versionInfo.```
=> fix: listSubheader material-ui warning

src/store/client/clientService.js
Updates listening from event name `error` to `pluginError` because when uncaught exceptions emit on `error` electron shows it in a blocking popup dialog to the user.
Event is updated in grid here: https://github.com/ethereum/grid/pull/321/commits/e5c38d22656876265f6e0e32fc56930c72787ed8
=> chore: update pluginError event name

src/components/Nodes/ClientConfig/DynamicConfigForm/FlagPreview.jsx
Fixes setting custom flags by passing `clientName` correctly
=> fix: pass clientName correctly to set custom flags

src/lib/utils.js, src/store/client/actions.js
Adds logic to rehydrate flags from `config.json` if exists.
=> fix: rehydrate flags

src/components/Nodes/ClientConfig/DynamicConfigForm/FlagPreview.jsx, src/components/Nodes/ClientConfig/DynamicConfigForm/index.js
* Checks if flags are custom on render to check 'Edit' checkbox
* Also, resets flags to generated on uncheck of checkbox
=> fix: checks if flags are custom on render to check 'Edit' checkbox

src/store/client/clientService.js
Removes only the listeners that grid-ui has started itself.
Closes https://github.com/ethereum/grid/issues/368
=> fix: changes from removeAllListeners to removeListeners + callback

src/components/Nodes/ClientConfig/index.js, src/store/client/actions.js, src/store/client/clientService.js, src/store/client/reducer.js, src/store/client/reducer.test.js
Supports taking in multiple plugin errors to display in UI
also, includes an update to not forcefully update redux state to `error`
=> feat: multiple errors

src/components/shared/Notification.js, src/store/client/actions.js
Handles error message objects in `Notification`s
Reproduce by starting parity, stopping, starting again.
=> fix: handle error object notifications

src/components/Plugins/index.js, src/lib/utils.js, src/store/plugin/actions.js, src/store/plugin/reducer.js, src/store/plugin/reducer.test.js
`client` -> `plugin` naming updates for all Redux files, utils, and the Plugins index file. 
Only several hundred more `client` references remaining in the app 😅 
Partially addresses https://github.com/ethereum/grid/issues/395 and https://github.com/ethereum/grid/issues/394
=> fix: plugin name refactor v3

src/store/plugin/clientService.js, src/store/plugin/pluginService.js
Simplifies PluginService by refactoring away the client funcs into a separate ClientService file
=> chore: refactor client PluginService funcs into ClientService

src/components/Plugins/PluginConfig/DynamicConfigForm/FormItem.js, src/components/Plugins/PluginConfig/DynamicConfigForm/index.js, src/components/Plugins/PluginConfig/index.js, src/components/Plugins/PluginsNav.js, src/components/Plugins/PluginsNavListItem.js, src/components/Plugins/Terminal/TerminalInput.js, src/components/Plugins/Terminal/index.js, src/components/Plugins/index.js, src/lib/utils.js, src/test/settings.test.js
- `ServicesNav` -> `PluginsNav`
- `ServicesNavListItem` -> `PluginsNavListItem`
- utils refactor
- settings test refactor
- etc. `client`/`service` -> `plugin` refactors.
Finishes this task, with the exception of NodeInfo components, which @ryanio has addressed in another PR.
Closes https://github.com/ethereum/grid/issues/394
=> chore: refactor service to plugin

README.md, docs/CONTRIBUTING.md
Mimics much of the ethereum/grid README. I think the grid proper repo ought to be the primary "source of truth", so this repeats the basics and points back there.
=> chore: update README with latest links/screenshot

src/components/Plugins/PluginConfig/DynamicConfigForm/FlagPreview.js
Small bug fix, I noticed FlagPreview wasn't being disabled while the plugin was running.
=> fix: disable FlagPreview on running

src/components/Apps/AppItem.js, src/components/Plugins/PluginConfig/AboutPlugin.js, src/components/Plugins/PluginConfig/DynamicConfigForm/FormItem.js, src/components/Plugins/PluginConfig/index.js, src/store/plugin/actions.js, src/store/plugin/reducer.js
* Adds an `About` tab as the first tab on plugins
* Renames `Details` tab to `Metadata`
---
To be paired with https://github.com/ethereum/grid/pull/426
---
---
Closes https://github.com/ethereum/grid/issues/422
=> feat: About tab

src/components/Plugins/PluginConfig/DynamicConfigForm/index.js
Introduces `required` flags. Half of closing https://github.com/ethereum/grid/issues/442
I like this solution because: 
A) the plugin config code is a little verbose, but requires no changes to the complicated flag generation logic, and 
B) users can still go wild and override the flags in the custom flag section
Note: assuming you have some stored values for Parity configs, you will likely have to toggle custom flags on and off to see the new ones appear.
=> feat: omits required settings from form UI

package.json
Bumps `grid-ui` version to `0.1.31`
=> chore: bump grid-ui version

src/components/Plugins/PluginView/index.js
Fixes horizontal scrolling bug when `Metadata` tab is selected.
Styles from the Terminal component were copy-pasted into this component, but never applied.
Closes https://github.com/ethereum/grid/issues/373
=> fix: excess width in metadata

src/components/Apps/AppItem.js, src/components/Plugins/PluginConfig/AboutPlugin.js, src/components/Plugins/PluginConfig/index.js, src/components/Plugins/PluginsNavListItem.js, src/store/plugin/actions.js, src/store/plugin/pluginService.js, src/store/plugin/reducer.js
Plugins can now emit `setAppBadge({appId, count})` and provide `plugin.api.getAppBadges()`, to put an app badge over an app.
An app badge object looks like: `{'grid-clef-app': 2}`
---
Branch pairs with https://github.com/ethereum/grid/pull/227
=> feat: App Badges

src/components/Webview/index.jsx
Shows `404` page to user if an app fails to load. currently is just blank screen.
WIP: works in dev, needs more work to load `404.html` file path properly in prod
=> fix: show 404 on app load fail

src/components/Plugins/NodeInfo/NodeInfoBox.js, src/components/Plugins/PluginsNav.js
Fixes node info positioning with new grid-ui layout. 
It would be ideal to not use absolute positioning so it doesn't break every time the layout changes, but this is a quick fix for now to move onto more important tasks.
=> fix: node info position

src/components/Plugins/NodeInfo/NodeInfoDot.js, src/components/Plugins/NodeInfo/index.js, src/components/Plugins/PluginConfig/DynamicConfigForm/FormItem.js
* Restores pulse on new block
* Fixes dynamic config itemValue warning
=> fix: pulse on new block

src/components/Plugins/PluginConfig/index.js
Fixes https://github.com/ethereum/grid/issues/418
* Dispatches `clearPluginErrors` on Terminal tab click or closing error.
* Adds error count badge on Terminal tab.
Pairs with https://github.com/ethereum/grid/pull/446
=> feat: clearPluginErrors for nano

package.json, src/components/App.js, src/components/Plugins/PluginConfig/DynamicConfigForm/FlagPreview.js, src/components/Plugins/PluginConfig/index.js, src/components/shared/Notification.js, src/store/plugin/actions.js, src/store/plugin/pluginService.js, src/store/plugin/reducer.js, src/store/plugin/reducer.test.js, yarn.lock
Use `notistack` to stack snackbars so they don't overlap
Also uses new `getErrors` and `dismissError(key)` in grid: https://github.com/ethereum/grid/pull/468
Also converts FlagPreview to use notistack (and incorporates https://github.com/ethereum/grid-ui/pull/148)
Closes https://github.com/ethereum/grid/issues/467
Closes https://github.com/ethereum/grid/issues/466
---
=> feat: use notistack

src/components/Plugins/PluginConfig/index.js
Adds `setup-event` status to grid-ui, sync'd with nano.
=> feat: display `setup-event` status

src/components/Plugins/PluginView/index.js
Merging wiped out some styling fixes on plugin code. See 'before' screenshot. Fixes https://github.com/ethereum/grid/issues/475.
before: 
after:
=> fix: remove terminal styling

src/components/Plugins/NodeInfo/NodeInfoDot.js, src/components/Plugins/PluginConfig/DynamicConfigForm/FlagPreview.js, src/components/Plugins/PluginConfig/DynamicConfigForm/FormItem.js, src/components/Plugins/PluginConfig/DynamicConfigForm/index.js, src/components/Plugins/PluginConfig/index.js, src/components/Plugins/index.js, src/components/shared/Select.js, src/lib/utils.js, src/store/plugin/actions.js
- Adds a `Restore Defaults` button to the bottom of the settings page.
- Fixes multiple custom flags warnings
- Additional cleanup along the way
- Did some pruning along the way. The logic around settings and flag generation is still difficult to parse and kind of a mess. 
- `Select` component was buggy, not updating on new `value` prop updates
- Debounced the flag input field for performance. I think all text input fields now immediately update local state and debounce redux cycles.
https://imgur.com/jwxbVLI
Closes https://github.com/ethereum/grid/issues/485
Closes https://github.com/ethereum/grid/issues/478
=> feat: restore default settings

src/components/Plugins/PluginConfig/VersionList/VersionListItem.js
Handles undefined platform and arch values when displaying bin versions
=> fix: hide undefined bin values

src/components/Plugins/Metadata/index.js, src/components/Plugins/PluginConfig/index.js
- renames PluginView -> Metadata
- hides author-related fields until logic implemented
It's a bad look to display our maintained plugins as untrusted.
=> chore: metadata rename
